### ISSUE TITLE
Having trouble with standalone Panini directions: CLI says 'command not found'

### ISSUE THREAD

**Issue by aalokt89** [foundation/panini#172]
I love the power of panini, but I want to use it without the Zurb stack. I'm trying to set up my project but the documentation is very thin and not detailed for beginners (I'm admittedly a beginner with gulp). Is there a detailed guide or simple example project example anywhere?

Steps I've taken so far:
1. `npm init`
2. `npm install panini --save-dev`
3. `npm install gulp --save-dev`
4. (?) Manually created the proper file structure (src/pages, layouts, partials, data, components assets | dist) (?)
5. Created a new gulpfile.js and copied the snippet from github:
```
var gulp = require('gulp');
var panini = require('panini');

gulp.task('default', function() {
  gulp.src('pages/**/*.html')
    .pipe(panini({
      root: 'pages/',
      layouts: 'layouts/',
      partials: 'partials/',
      helpers: 'helpers/',
      data: 'data/'
    }))
    .pipe(gulp.dest('build'));
});

gulp.watch(['./src/{layouts,partials,helpers,data}/**/*'], [panini.refresh]);
```
Now I'm not really sure what to do. I also tried via the CLI with `panini --root=src/pages --layouts=src/layouts --partials=src/partials --data=src/data --output=dist 'src/pages/**/*.html` but I get a 'command not found' error. Any help would be much appreciated!

**Comment by DanielRuf** [comment]
Closing as stale.
