### ISSUE TITLE
Gulp 4.0 setup for panini

### ISSUE THREAD

**Issue by muhamed91** [foundation/panini#185]
This Gulp setup wont work on the Gulp 4.0 you should downgrade the version or your have to use:

`gulp.watch(['./src/{layouts,partials,helpers,data}/**/*'], [panini.refresh]);` version 3.0

`gulp.watch(['./src/{layouts,partials,helpers,data}/**/*'], gulp.series([panini.refresh]));` version 4.0

**Comment by DanielRuf** [comment]
That's because gulp 4 brought some breaking changes regarding its API.
