### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by cssninjaStudio** [foundation/panini#193]
@gakimball Hi, Iam posting this as I saw you were the last active contributor on panini. Is it dead or will someone support it? I have to say there is no similar tool available, and it is so great for designers who want to uickly mock something on their screen or develop complex UI templates. Features are completely satisfying for now and we can even add custom helpers. It still works pretty well in a Gulp 4 node-sass setup and saves a lot of development time.

Would that be possible to at least have the dependencies updated ? Would give some fresh air to panini, the best flat compiler around. 

Thanks for considering this matter.

**Comment by DanielRuf** [comment]
We are currently working on Foundation 6.6 and we will have more time then.
