### ISSUE TITLE
Panini template code

### ISSUE THREAD

**Issue by kaydwithers** [foundation/panini#55]
I'm having trouble working out how to add Panini template code.

I have a link which I want to add .yml to build the tracking URL. i.e

in my src/data/_tracking.yml file

```
url: http://zurb.com
date: 16.6.2016
campaign: june 
```

in my src/pages/index.html file

```
<a target="_blank" href="{{ tracking.url }}/{{ tracking.date }}/{{ tracking.campaign }}">
  <img src="../assets/img/hero.jpg" alt="">
</a>
```

Could someone please help me out and let me know how this can be done or let me know why this doesn't work?

**Comment by fdeneux** [comment]
Try without the underscore:
src/data/**tracking**.yml

**Comment by kaydwithers** [comment]
@fdeneux I'm afraid that doesn't work. I believe the tracking.yml needs to be setup? i.e in Jekyll, you would write something like..

```
{% for user in data.tracking %} 
  <a href="{{ tracking.url }}"></a>
{% endfor %}
```

Do you know how this can be done in Panini. And Is this something can be added to the Panini docs?

**Comment by fdeneux** [comment]
@kaydwithers With the information you have given, the error was certainly the underscore. If it still doesn't work I'm afraid you will have to be more specific.

**Comment by kaydwithers** [comment]
@fdeneux I have removed the underline and it still does not work. I guess what I'm trying to figure out is how does the handlebar know to look in the src/data/tracking.yml file for the {{ tracking.url }} information? Is it something that Panini does automatically?

**Comment by fdeneux** [comment]
That is absolutely possible and yes it is something that Panini does automatically IF configured correctly in your gulpfile.

```
root
└───src
    ├───data
    │   └───tracking.yml
    ├───layouts
    │   └───default.html
    ├───pages
    │   └───index.html
    └───partials
```

tracking.yml

```yml
---
url: http://zurb.com
date: 16.6.2016
campaign: april
```

index.html

```html
---
image:
    image-01: image.jpg
---

<a target="_blank" href="{{ tracking.url }}/{{ tracking.date }}/{{ tracking.campaign }}">
    <img src="{{ image.image-01 }}" alt="">
</a>
```

Should be working just fine.

**Comment by kaydwithers** [comment]
Thanks @fdeneux, I just need a little more help with the Gulp file. I'm not sure how to add my data. I tried doing it with the below code in my `gulpfile.babel.js` file but no luck.

`// Compile layouts, pages, and partials into flat HTML files
// Then parse using Inky templates
function pages() {
  return gulp.src('src/pages/**/*.html')
    .pipe(panini({
      root: 'src/pages',
      data: 'src/data',
      layouts: 'src/layouts',
      partials: 'src/partials',
      helpers: 'src/helpers'
    }))
    .pipe(inky())
    .pipe(gulp.dest('dist'));
}`

**Comment by webuxr** [comment]
@kaydwithers ...just stumbled upon this thread and am wondering if you might have missed the `data`, `layouts`, `pages`, and `partials` nodes being nested within `src` and that too nested within `root`? If I edit your Gulp function, it might look like this:

```javascript
function pages() {
  return gulp.src('src/pages/**/*.html')
    .pipe(panini({
      root: {
        src: {
          layouts: 'src/layouts/',
          partials: 'src/partials/',
          data: 'src/data/',
          helpers: 'src/helpers/'
        }
      }
    }))
    .pipe(inky())
    .pipe(gulp.dest('dist'));
}
```

Please do not take this code example as a working solution. I am stuck at the same place you are! It just seems you are a bit father ahead of me in your troubleshooting, and after seeing this issue, thought I could offer a hand.

Try it. Does it work?

**Comment by webuxr** [comment]
> Try it. Does it work?

...then notices the date of the author's post. SMH.

**Comment by DanielRuf** [comment]
Closing as stale.
